// Auto-generated by Light & Moment Admin
// Last updated: 5/8/2026, 4:52:13 PM

const SITE_CONFIG = {
  "name": "Your Name",
  "tagline": "Light & Moment",
  "taglineZh": "光与瞬间",
  "email": "hello@yourname.com",
  "instagram": "yourname",
  "bioEn": "Based in the San Francisco Bay Area, I'm a portrait photographer with five years of experience.",
  "bioZh": "旧金山湾区人像摄影师，五年拍摄经验。"
};

const SERIES = [
  {
    "id": "portrait-lan-202605",
    "name": "我在大岛天气晴",
    "date": "May 2026",
    "category": "portrait",
    "cover": "https://res.cloudinary.com/dpadfus0q/image/upload/v1778290589/portfolio/ibjdm0xtlaxqxtnrul8v.jpg",
    "photos": [
      "https://res.cloudinary.com/dpadfus0q/image/upload/v1778290589/portfolio/ibjdm0xtlaxqxtnrul8v.jpg",
      "https://res.cloudinary.com/dpadfus0q/image/upload/v1778290591/portfolio/qhvk4onp718u4rtcavoq.jpg",
      "https://res.cloudinary.com/dpadfus0q/image/upload/v1778290586/portfolio/v4ihjeieyn6gu8xm8ajl.jpg",
      "https://res.cloudinary.com/dpadfus0q/image/upload/v1778290587/portfolio/hqb8sirfwpwiltkyfdvw.jpg",
      "https://res.cloudinary.com/dpadfus0q/image/upload/v1778290585/portfolio/bcp11obowwbgbeobufdn.jpg",
      "https://res.cloudinary.com/dpadfus0q/image/upload/v1778290587/portfolio/zishcjguofpf7heytvms.jpg",
      "https://res.cloudinary.com/dpadfus0q/image/upload/v1778290799/portfolio/dl8ds95sa2tte5ltbxah.jpg",
      "https://res.cloudinary.com/dpadfus0q/image/upload/v1778290588/portfolio/mvvx9mfkygvk45tkfyvz.jpg",
      "https://res.cloudinary.com/dpadfus0q/image/upload/v1778290589/portfolio/ikc3wqro9gbwsayilywp.jpg",
      "https://res.cloudinary.com/dpadfus0q/image/upload/v1778290594/portfolio/phlkyahe8jrauiwweyub.jpg",
      "https://res.cloudinary.com/dpadfus0q/image/upload/v1778290592/portfolio/klqdmaapgqjvfglus1ll.jpg",
      "https://res.cloudinary.com/dpadfus0q/image/upload/v1778290593/portfolio/wbxierfntyc8mqfxxiga.jpg"
    ]
  },
  {
    "id": "portrait-Liz-202407",
    "name": "Summer Story",
    "date": "July 2024",
    "category": "portrait",
    "cover": "https://res.cloudinary.com/dpadfus0q/image/upload/v1778290928/portfolio/xslep9s6fkcf0h8ap7vd.jpg",
    "photos": [
      "https://res.cloudinary.com/dpadfus0q/image/upload/v1778290928/portfolio/xslep9s6fkcf0h8ap7vd.jpg",
      "https://res.cloudinary.com/dpadfus0q/image/upload/v1778290929/portfolio/dnu7s0oqq6w6zk99hs12.jpg",
      "https://res.cloudinary.com/dpadfus0q/image/upload/v1778290931/portfolio/b0gnz3iuelsqgzbcbveu.jpg",
      "https://res.cloudinary.com/dpadfus0q/image/upload/v1778290932/portfolio/uvvk6dzcdaz3aqxzcbkx.jpg",
      "https://res.cloudinary.com/dpadfus0q/image/upload/v1778290933/portfolio/b3uyfxy9wcvhxwsx1se8.jpg"
    ]
  },
  {
    "id": "portrait- Rachel-202409",
    "name": "那年夏天宁静的海",
    "date": "Sep 2024",
    "category": "portrait",
    "cover": "https://res.cloudinary.com/dpadfus0q/image/upload/v1778291276/portfolio/saoztwtut8my3qy26yf7.jpg",
    "photos": [
      "https://res.cloudinary.com/dpadfus0q/image/upload/v1778291276/portfolio/saoztwtut8my3qy26yf7.jpg",
      "https://res.cloudinary.com/dpadfus0q/image/upload/v1778291277/portfolio/e4qis7wxwuqcjuysgwh2.jpg",
      "https://res.cloudinary.com/dpadfus0q/image/upload/v1778291278/portfolio/ltv4tmidwgubyukbssof.jpg",
      "https://res.cloudinary.com/dpadfus0q/image/upload/v1778291279/portfolio/qnjthnzn08okfixz1395.jpg",
      "https://res.cloudinary.com/dpadfus0q/image/upload/v1778291279/portfolio/p6ck9wk30fbiyxyviex5.jpg",
      "https://res.cloudinary.com/dpadfus0q/image/upload/v1778291280/portfolio/niinptvmd77axbarigiu.jpg",
      "https://res.cloudinary.com/dpadfus0q/image/upload/v1778291281/portfolio/ptlkjhtdoobqaylhgf0n.jpg",
      "https://res.cloudinary.com/dpadfus0q/image/upload/v1778291282/portfolio/r0srvykizqnladdfh34i.jpg",
      "https://res.cloudinary.com/dpadfus0q/image/upload/v1778291282/portfolio/qywpzrddqhgic7m0uppz.jpg",
      "https://res.cloudinary.com/dpadfus0q/image/upload/v1778291283/portfolio/ju9y588g7jp4gzoj4vvt.jpg",
      "https://res.cloudinary.com/dpadfus0q/image/upload/v1778291284/portfolio/mdetcw18whxaiphidckl.jpg",
      "https://res.cloudinary.com/dpadfus0q/image/upload/v1778291412/portfolio/ttvhfw2qfz7dqv6jcypk.jpg"
    ]
  }
];

const CLIENT_ALBUMS = [];

const FEATURED_PHOTOS = [];
