// Auto-generated by Light & Moment Admin
// Last updated: 5/11/2026

const SITE_CONFIG = {
  "name": "Yang",
  "tagline": "Told By Light | 光语",
  "taglineZh": "Photography by Yang",
  "email": "yang.sherry.wang@gmail.com",
  "instagram": "told_by_light_photography",
  "bioEn": "Based in the San Francisco Bay Area, I'm a portrait photographer with five years of experience — drawn to light, emotion, and the fleeting moments that deserve to be remembered.",
  "bioZh": "旧金山湾区人像摄影师，五年拍摄经验。着迷于光线与情感，以及那些值得被珍藏的瞬间。"
};

const SERIES = [
  {
    "id": "wedding-lovely-2024",
    "name": "City Hall Moment",
    "date": "July 2024",
    "category": "wedding",
    "cover": "https://res.cloudinary.com/dpadfus0q/image/upload/v1778558017/portfolio/oconhbpxzkjuwaieaeem.jpg",
    "photos": [
      "https://res.cloudinary.com/dpadfus0q/image/upload/v1778558017/portfolio/oconhbpxzkjuwaieaeem.jpg",
      { "src": "https://res.cloudinary.com/dpadfus0q/image/upload/v1778558018/portfolio/ky2m0fre0oqq9zhcu9zd.jpg", "landscape": true },
      { "src": "https://res.cloudinary.com/dpadfus0q/image/upload/v1778558021/portfolio/w65vzmjlzd9xp5avjsfi.jpg", "landscape": true },
      "https://res.cloudinary.com/dpadfus0q/image/upload/v1778558022/portfolio/tdod4yb7ducaruq9xetb.jpg",
      "https://res.cloudinary.com/dpadfus0q/image/upload/v1778558023/portfolio/qhr6soiojqtaxk09ulf8.jpg",
      "https://res.cloudinary.com/dpadfus0q/image/upload/v1778558024/portfolio/yzi5mm790gwtadwzor9n.jpg",
      "https://res.cloudinary.com/dpadfus0q/image/upload/v1778558025/portfolio/priqfezovvuk9c1mtmdm.jpg",
      "https://res.cloudinary.com/dpadfus0q/image/upload/v1778558027/portfolio/s65ee0rejpbkwg2axc7f.jpg"
    ]
  },
  {
    "id": "portrait-lan-202605",
    "name": "我在大岛天气晴",
    "date": "May 2026",
    "category": "portrait",
    "cover": "https://res.cloudinary.com/dpadfus0q/image/upload/v1778290589/portfolio/ikc3wqro9gbwsayilywp.jpg",
    "photos": [
      "https://res.cloudinary.com/dpadfus0q/image/upload/v1778290589/portfolio/ikc3wqro9gbwsayilywp.jpg",
      "https://res.cloudinary.com/dpadfus0q/image/upload/v1778290592/portfolio/klqdmaapgqjvfglus1ll.jpg",
      "https://res.cloudinary.com/dpadfus0q/image/upload/v1778290586/portfolio/v4ihjeieyn6gu8xm8ajl.jpg",
      "https://res.cloudinary.com/dpadfus0q/image/upload/v1778290587/portfolio/hqb8sirfwpwiltkyfdvw.jpg",
      "https://res.cloudinary.com/dpadfus0q/image/upload/v1778290585/portfolio/bcp11obowwbgbeobufdn.jpg",
      "https://res.cloudinary.com/dpadfus0q/image/upload/v1778290587/portfolio/zishcjguofpf7heytvms.jpg",
      "https://res.cloudinary.com/dpadfus0q/image/upload/v1778290588/portfolio/mvvx9mfkygvk45tkfyvz.jpg",
      "https://res.cloudinary.com/dpadfus0q/image/upload/v1778290589/portfolio/ibjdm0xtlaxqxtnrul8v.jpg",
      "https://res.cloudinary.com/dpadfus0q/image/upload/v1778290593/portfolio/wbxierfntyc8mqfxxiga.jpg"
    ]
  },
  {
    "id": "portrait-Rachel-202409",
    "name": "那年夏天宁静的海",
    "date": "Sep 2024",
    "category": "portrait",
    "cover": "https://res.cloudinary.com/dpadfus0q/image/upload/v1778291276/portfolio/saoztwtut8my3qy26yf7.jpg",
    "photos": [
      "https://res.cloudinary.com/dpadfus0q/image/upload/v1778291276/portfolio/saoztwtut8my3qy26yf7.jpg",
      "https://res.cloudinary.com/dpadfus0q/image/upload/v1778291412/portfolio/ttvhfw2qfz7dqv6jcypk.jpg",
      "https://res.cloudinary.com/dpadfus0q/image/upload/v1778291281/portfolio/ptlkjhtdoobqaylhgf0n.jpg",
      "https://res.cloudinary.com/dpadfus0q/image/upload/v1778291277/portfolio/e4qis7wxwuqcjuysgwh2.jpg",
      "https://res.cloudinary.com/dpadfus0q/image/upload/v1778291282/portfolio/qywpzrddqhgic7m0uppz.jpg",
      "https://res.cloudinary.com/dpadfus0q/image/upload/v1778291279/portfolio/qnjthnzn08okfixz1395.jpg",
      { "src": "https://res.cloudinary.com/dpadfus0q/image/upload/v1778291282/portfolio/r0srvykizqnladdfh34i.jpg", "landscape": true },
      { "src": "https://res.cloudinary.com/dpadfus0q/image/upload/v1778291283/portfolio/ju9y588g7jp4gzoj4vvt.jpg", "landscape": true }
    ]
  },
  {
    "id": "portrait-Liz-202407",
    "name": "Summer Story",
    "date": "July 2024",
    "category": "portrait",
    "cover": "https://res.cloudinary.com/dpadfus0q/image/upload/v1778290928/portfolio/xslep9s6fkcf0h8ap7vd.jpg",
    "photos": [
      "https://res.cloudinary.com/dpadfus0q/image/upload/v1778290928/portfolio/xslep9s6fkcf0h8ap7vd.jpg",
      "https://res.cloudinary.com/dpadfus0q/image/upload/v1778290931/portfolio/b0gnz3iuelsqgzbcbveu.jpg",
      "https://res.cloudinary.com/dpadfus0q/image/upload/v1778290933/portfolio/b3uyfxy9wcvhxwsx1se8.jpg",
      { "src": "https://res.cloudinary.com/dpadfus0q/image/upload/v1778290929/portfolio/dnu7s0oqq6w6zk99hs12.jpg", "landscape": true },
      { "src": "https://res.cloudinary.com/dpadfus0q/image/upload/v1778296135/portfolio/dcuhb3iswxdtj4bnttqr.jpg", "landscape": true }
    ]
  }
];

const CLIENT_ALBUMS = [];

const FEATURED_PHOTOS = [];
